Repository paratestphp/paratest, pull requests merged in 2022-12, with the labels that each got.

#705 Update to PSalm 5
  Makefile
  composer.json
  src/Logging/JUnit/TestCase.php
  test/Unit/Coverage/CoverageReporterTest.php
Labels: dependency-update

#708 Support PHP 8.2
  .github/workflows/integrate.yaml
  composer.json
Labels: phpunit compatibility, dependency-update

#714 WrapperRunner: add `--max-batch-size` support
  README.md
  composer.json
  infection.json
  src/Runners/PHPUnit/WrapperRunner.php
  test/Unit/Runners/PHPUnit/WrapperRunnerTest.php
  test/fixtures/phpunit-wrapper-batchsize-suite.xml
  test/fixtures/wrapper_batchsize_suite/FourTest.php
  test/fixtures/wrapper_batchsize_suite/OneTest.php
  test/fixtures/wrapper_batchsize_suite/ThreeTest.php
  test/fixtures/wrapper_batchsize_suite/TwoTest.php
  test/fixtures/wrapper_batchsize_suite/WrapperBatchTestCase.php
  test/fixtures/wrapper_batchsize_suite/tmp/pid/.gitignore
  test/fixtures/wrapper_batchsize_suite/tmp/token/.gitignore
Labels: enhancement
