Repository paratestphp/paratest, pull requests merged in 2022-06, with the labels that each got.

#666 CS: disable mysterious Squiz.Functions.FunctionDeclaration.Found issue
  .gitattributes
  .github/dependabot.yml
  .github/lint-xml-configuration/lint-xml-configuration.sh
  .github/workflows/integrate.yaml
  composer.json
  infection.json
  phpcs.xml
  phpstan.neon
  phpunit.xml
  psalm.xml
  test/TestBase.php
Labels: dependency-update

#668 Add version information
  composer.json
  src/Console/Commands/ParaTestCommand.php
  test/Unit/Console/Commands/ParaTestCommandTest.php
Labels: enhancement

#669 Fix stale action
  .github/workflows/stale.yml
Labels: bug, quality

#672 Add PHPStorm integration
  Makefile
  README.md
  bin/paratest_for_phpstorm
  phpcs.xml
  src/Runners/PHPUnit/Options.php
  src/Runners/PHPUnit/ResultPrinter.php
  src/Runners/PHPUnit/SuiteLoader.php
  src/Util/PhpstormHelper.php
  test/Unit/ResultTester.php
  test/Unit/Runners/PHPUnit/OptionsTest.php
  test/Unit/Runners/PHPUnit/ResultPrinterTest.php
  test/Unit/Runners/PHPUnit/RunnerTestCase.php
  test/Unit/Util/PhpstormHelperTest.php
Labels: enhancement

#673 UI feedback: get closer to PHPUnit's one
  .github/workflows/integrate.yaml
  Makefile
  composer.json
  docs/code-coverage.md
  phpunit.xml
  src/Console/Commands/ParaTestCommand.php
  src/Runners/PHPUnit/BaseRunner.php
  src/Runners/PHPUnit/Options.php
  src/Runners/PHPUnit/ResultPrinter.php
  src/Runners/PHPUnit/SuiteLoader.php
  src/Runners/PHPUnit/Worker/WrapperWorker.php
  test/Unit/Console/Commands/ParaTestCommandTest.php
  test/Unit/Runners/PHPUnit/BaseRunnerTest.php
  test/Unit/Runners/PHPUnit/EmptyRunnerStub.php
  test/Unit/Runners/PHPUnit/ResultPrinterTest.php
  test/Unit/Runners/PHPUnit/RunnerTestCase.php
  test/fixtures/phpunit-coverage-cache.xml
  test/fixtures/phpunit-coverage-text-show-only-summary.xml
  test/fixtures/phpunit-failing-listener.xml
  test/fixtures/phpunit-fully-configured.xml
Labels: enhancement, phpunit compatibility

#677 Fix export of bins
  composer.json
Labels: bug

#678 Make fixtures regenerable, do not flatten JUnit logs on merge
  Makefile
  composer.json
  psalm-baseline.xml
  src/Logging/JUnit/Reader.php
  src/Logging/JUnit/TestSuite.php
  src/Logging/JUnit/Writer.php
  src/Logging/LogInterpreter.php
  src/Runners/PHPUnit/ResultPrinter.php
  test/Unit/Coverage/CoverageMergerTest.php
  test/Unit/Logging/JUnit/ReaderTest.php
  test/Unit/Logging/JUnit/WriterTest.php
  test/Unit/Logging/LogInterpreterTest.php
  test/Unit/ResultTester.php
  test/Unit/Runners/PHPUnit/ResultPrinterTest.php
  test/fixtures/failing_tests/UnitTestWithMethodAnnotationsTest.php
  test/fixtures/parallel_suite/One/FourTest.php
  test/fixtures/parallel_suite/One/OneTest.php
  test/fixtures/results/data-provider-errors.xml
  test/fixtures/results/data-provider-result.xml
  test/fixtures/results/data-provider-with-special-chars.xml
  test/fixtures/results/junit-example-result.xml
  test/fixtures/results/mixed-results-with-system-out.xml
  test/fixtures/results/mixed-results.xml
  test/fixtures/results/multiple-errors-with-system-out.xml
  test/fixtures/results/parallel/01.xml
  test/fixtures/results/parallel/02.xml
  test/fixtures/results/parallel/03.xml
  test/fixtures/results/parallel/04.xml
  test/fixtures/results/parallel/05.xml
  test/fixtures/results/parallel/06.xml
  test/fixtures/results/parallel/07.xml
  test/fixtures/results/parallel/08.xml
  test/fixtures/results/parallel/09.xml
  test/fixtures/results/parallel/10.xml
  test/fixtures/results/parallel/combined.xml
  test/fixtures/results/single-method.xml
  test/fixtures/results/single-passing.xml
  test/fixtures/results/single-skipped.xml
  test/fixtures/results/single-warning.xml
  test/fixtures/results/single-werror.xml
  test/fixtures/results/single-werror2.xml
  test/fixtures/results/single-wfailure.xml
  test/fixtures/results/single-wfailure2.xml
  test/fixtures/special_chars/UnitTestWithDataProviderSpecialCharsTest.php
  test/fixtures/system_out/SystemOutTest.php
Labels: bug, enhancement
