Repository paratestphp/paratest, pull requests merged in 2023-10, with the labels that each got.

#794 Set `PHPUNIT_COMPOSER_INSTALL` before requiring the autoloader so it can access it
  bin/phpunit-wrapper.php
Labels: bug

#795 Set `PHPUNIT_COMPOSER_INSTALL` before requiring the autoloader so it can access it (#794)
  bin/phpunit-wrapper.php
Labels: bug

#797 Update PHPUnit compatibility to 10.4.0
  Makefile
  composer.json
  src/ParaTestCommand.php
  src/WrapperRunner/ApplicationForWrapperWorker.php
  src/WrapperRunner/WrapperRunner.php
  test/Unit/OptionsTest.php
  test/Unit/WrapperRunner/ResultPrinterTest.php
Labels: bug

#798 Activate Renovatebot
  .github/dependabot.yml
  .github/workflows/ci.yml
  renovate.json
Labels: dependency-update

#803 [7.x] Adds Symfony 7 support
  composer.json
Labels: dependency-update

#822 [6.x] Add Symfony 7 support
  composer.json
  src/Console/Commands/ParaTestCommand.php
  src/Logging/JUnit/Reader.php
  src/Logging/JUnit/TestCase.php
  src/Runners/PHPUnit/Suite.php
  src/Runners/PHPUnit/TestMethod.php
  test/Unit/Runners/PHPUnit/OptionsTest.php
  test/Unit/Runners/PHPUnit/WrapperRunnerTest.php
Labels: enhancement, dependency-update
