Repository paratestphp/paratest, pull requests merged in 2024-02, with the labels that each got.

#838 Add support for PHPUnit 11
  .github/workflows/ci.yml
  Makefile
  bin/phpunit-wrapper.php
  composer.json
  phpstan-baseline.neon
  src/WrapperRunner/ApplicationForWrapperWorker.php
  src/WrapperRunner/WrapperWorker.php
  test/Unit/WrapperRunner/WrapperRunnerTest.php
Labels: phpunit compatibility

#840 Fix `--testdox` output
  bin/phpunit-wrapper.php
  composer.json
  test/TestBase.php
  test/Unit/OptionsTest.php
  test/Unit/WrapperRunner/WrapperRunnerTest.php
  test/Unit/WrapperRunner/fixtures/common_results_testdox_output
Labels: bug

#841 Minor: no need to sort testdox assertions
  test/Unit/WrapperRunner/WrapperRunnerTest.php
  test/Unit/WrapperRunner/fixtures/common_results_testdox_output
Labels: enhancement

#828 Fix `--functional` progress output
  composer.json
  src/WrapperRunner/SuiteLoader.php
  test/Unit/WrapperRunner/WrapperRunnerTest.php
  test/fixtures/function_parallelization_tests/FunctionalParallelizationTest.php
Labels: bug

#842 Fix `--functional` progress output without a `dataProvider`
  src/WrapperRunner/SuiteLoader.php
  test/Unit/WrapperRunner/WrapperRunnerTest.php
  test/fixtures/same_beginning_of_name/SameBeginningOfNameTest.php
Labels: bug
